### PR TITLE
Adopt webpack public-path

### LINKED ISSUE #167: Allow assets path to be configurable
Currently webpack is configured to pack and link all the assets to / .

This is quite restrictive and limits the deployment, for instance to use github pages which would have assets at user.github.com/repo/asset.js

There could be used by having a public path configurable, as of the webpack documentation.[1]

[1] https://webpack.js.org/guides/public-path/

### PR DESCRIPTION
**Pull request by gustavomonarin**
Adopt webpack public path configuration in order to enable deployment
on github pages.

[ref] https://webpack.js.org/guides/public-path/

resolves #167

### CODE REVIEW

**Comment by timofurrer** [comment]
Is there a plan to actually merge this?

**Comment by jemerald** [comment]
Please consider merging this, so that we can host the application on a sub path of our site. Thanks

**Comment by jemerald** [comment]
Not a deal breaker, but this change does not take fix the image URL in the stylesheets, so the `/images/logo.png` would not show up

image

**Comment by jemerald** [comment]
I think https://github.com/thoughtworks/build-your-own-radar/pull/219 is a better solution than this one as it made all asset references relative. It does require a bit of touch ups though.

**Comment by Madhumitha2911** [comment]
We have updated the webpack configurations. Kindly merge with the new master , resolve conflicts and raise a new PR.

**Pull request closed without merging**
