### PR TITLE
Add howto in readme

### PR DESCRIPTION
**Pull request by endremm**

### CODE REVIEW

**Comment by endremm** [comment]
Ended up on the wrong remote!

**Comment by endremm** [comment]
This PR was pushed to wrong repo, @Vaishnavij. Since it's just noise, could you please help me delete this PR totally?

Thank you.

**Comment by Vaishnavij** [comment]
@endremm : According to Github's policies I cannot delete the PR's directly.  If the PR contains sensitive information and needs to be deleted, I can connect with Github Support to delete it. Kindly let me know how would you like to proceed.

Thanks,
Vaishnavi Jayakumar

**Comment by endremm** [comment]
It would be nice if this PR could be deleted, even if it's not directly containing sensitive information. I did not see that the PR had wrong base before pushing the create button in the UI.

Thank you, @Vaishnavij!

**Pull request closed without merging**
