### PR TITLE
add csv support functionality

### PR DESCRIPTION
**Pull request by hkurosawa**
added functionality to read csv file (like hosted on github or any other URLs) and plot radar.

csv file format is as follows(1st line is column names)
------------------------
name,isNew,description,quadrant,ring
aName,False,aDescription,aQuad,adopt
bName,False,bDescription,bQuad,trial
cName,False,cDescription,cQuad,assess
dName,False,dDescription,dQuad,hold

### CODE REVIEW

**Comment by SARAN-thala** [comment]
Hi @hkurosawa ,
Thanks for building this for us.
Apologies for the delay. We have tested your PR and we have a few thoughts on it.

1. We validate the data that comes from Google sheets - please refer to factory.js for that. These validations are missing when we load the data from the url for a CSV document. Please add those validations. Just a suggestion, please feel free to refactor factory.js to avoid duplication.

2. Please update the Readme file to reflect about the usage of URL of CSV data as well.

Looking forward to hear back from you soon!

Thanks a ton,
ThoughtWorks team

**Comment by mostrovoi** [comment]
when running npm run dev with this pull request I get the following error:
ERROR in ./~/xmlhttprequest/lib/XMLHttpRequest.js
Module not found: Error: Cannot resolve module 'child_process'

**Comment by hkurosawa** [comment]
@mostrovoi I cannot reproduce the issue, plz try to execute
`npm install ` to make sure you have installed dependent packages before running `npm run dev` .

**Comment by hkurosawa** [comment]
Hi @sahrosa thank you for your review,
just added data verification & sanitization, as well as README update so could you please check the commit again?

**Comment by hkurosawa** [comment]
sorry, just some syntax fix on README ;)

**Comment by mostrovoi** [comment]
Yes, you are right. your pull request is just fine. Sorry about that.
Problem was that I cloned your repository directly and accessed branch csvsupport. You have still to apply this commit there (in csvsupport branch in your own repo) otherwise fails:

https://github.com/thoughtworks/build-your-own-radar/commit/190fefecf56e3f6b7ea62e3d67987b0e11a306e9

**Comment by hkurosawa** [comment]
Thank you @mostrovoi , I missed the latest commit.
I merged the 190fefe commit and push it to my csvsupport branch.

**Pull request merged**
