### PR TITLE
Added the ability to search data points in the radar. This closes thoughtworks/build-your-own-radar#4

### PR DESCRIPTION
**Pull request by aschonfeld**
I couldn't get the jasmine tests to run for radar-spec.js, but then I realized that they were marked with `xdescribe` anyways.

This PR makes use of the the standard jquery-ui autocomplete component and leverages the functions already defined by `selectQuadrant` to do the highlighting.

### CODE REVIEW

**Comment by CBeeson** [comment]
Yay thanks @aschonfeld this is really great. @lauraionescu @thenano can we get this merged?

**Comment by thenano** [comment]
@CBeeson I no longer work at TW so not sure I should be the one to push the button. But happy to push it if needed!
@rdoh @lauraionescu @arunvelsriram ?

**Comment by arunvelsriram** [comment]
@rdoh @lauraionescu and I no longer work for for this project.

@snehavas @viveksoundrapandi @mohamednajiullah can you please help here?

**Comment by arunvelsriram** [comment]
@snehavas @viveksoundrapandi @mohamednajiullah gentle bump!

**Comment by mohamednajiullah** [comment]
Hello @aschonfeld 

Thank you for this PR. We've taken this PR into consideration. We're waiting for approval from our product owners to merge this.

Thank you,
The BYOR Team

**Comment by CBeeson** [comment]
Yay glad to hear it @mohamednajiullah 
Do you have any idea when this is likely to be merged (days, weeks months?)? I'm wondering if i wait for this or release the fork.
Thanks!

**Comment by CBeeson** [comment]
@snehavas @viveksoundrapandi @mohamednajiullah gentle bump for an eta for merging this (days, weeks, months?)

**Comment by mohamednajiullah** [comment]
Hello @CBeeson 

We are evaluating this PR right now. We'll update you with the schedule in a day or two.

Thanks,
The BYOR Team

**Comment by CBeeson** [comment]
> Hello @CBeeson
> 
> We are evaluating this PR right now. We'll update you with the schedule in a day or two.
> 
> Thanks,
> The BYOR Team

Yay! Any feedback? (I work with @aschonfeld btw so can let him know if you do. Thanks

**Comment by mohamednajiullah** [comment]
Hello @aschonfeld, @CBeeson 

We evaluated the PR. We noted that to enable the autocomplete feature, the jquery autocomplete is used. However the npm package used is `jquery-ui-bundle`, which is not an official jquery package, instead of the `jquery-ui` package. 

We are not able to merge this PR since it uses an unofficial `jquery-ui` package. We would be happy to merge if you can submit this PR after changing the package.

Thanks,
The BYOR team.

**Comment by aschonfeld** [comment]
Updates have been made, please let me know if you need anything else.

**Comment by mohamednajiullah** [comment]
Hello @aschonfeld,

Thank you so much for the speedy fix. As part of improving the deployment process, we recently modified the deployment pipeline to run all tests when a PR is raised. When we tried to merge your PR, the tests didn't run because of some issues.

We believe the tests didn't run when you raised this PR because we changed the deployment pipeline after you raised this PR. Would it be possible for you to raise a new PR after fixing the tests? You can refer to the README on how to run the tests.

Thanks,
The BYOR team.

**Comment by aschonfeld** [comment]
I rebased my branch to what you have in master and now it should include your new deployment pipeline.  

There was no information in the README on how to run your cypress tests, luckily package.json was pretty self-explanatory.

A couple other modifications I had to make in order to get the travis build working:

- I added webpack's expose-loader and some default mappings to jquery so that some jquery warnings I was seeing in my browser went away (it was complaing about a missing reference to JQuery)
- I had to add jsdom so that I could inject jquery & jquery-ui to the jasmine tests using a helper script 'spec/helpers/jsdom.js'

One last note, it looks like the last step of your Travis build will never pass because you're not specifying a value for $TEST_URL.  I was not able to test my new Cypress test for the search functionality because our corporate proxy would not allow the Cypress to grab the google doc.  I was hoping that Travis woudl validate my new test, but my previous statement proved otherwise.  If someone could tell what $TEST_URL should be set to I can update .travis.yml in my PR.

Thanks,
Andy

**Pull request merged**
