### PR TITLE
Enable loading CSV hosted in same location

### LINKED ISSUE #111: Load CSVs hosted on same Location (e.g. GitHub pages)
What modifications would be necessary to be able to load csv files which are hosted on the same location but behind a proxy like on GitHub Enterprise Pages?d

Example:
- GitHub Enterprise
  - Project Repo
     - docs
       - radar
         - index.html ...
       - sheets
         - examplefile.csv

### PR DESCRIPTION
**Pull request by jonashartmann**
I've included a CSV file generated from the latest [ThoughtWorks Technology Radar Vol. 22](https://docs.google.com/spreadsheets/d/1M7eklh1oDrQpn9c0MTBHYJIG8apr5ulax7fPwVS7_-s/edit#gid=0)

Closes #111

### CODE REVIEW

**Review by dolanj1 — COMMENTED** [review]
nice!

**Comment by dcasati** [comment]
just adding to your efferots here @jonashartmann, I've created the following PR: #176 

in a nutshell -

I've worked on some changes and got into a point where this is working for me. Here's a quick way to test it:

```
$ docker pull dcasati/build-your-own-radar
$ docker run --rm -p 8080:80 -e SERVER_NAMES="localhost 127.0.0.1" -v /mnt/radar/sheets/:/opt/build-your-own-radar/sheets dcasati/build-your-own-radar
$ open http://localhost:8080
```

This will:

1. spawn a server that will listen locally on port 8080
1. mount the host volume on /mnt/radar/sheets/ into the container on /opt/build-your-own-radar/sheets/.
 1. open http://localhost:8080 and for the URL piece '(Enter the URL of your Google Sheet of CSV file bellow...)' type: http://localhost:8080/sheets/${NAME_OF_YOUR_SHEET}.csv - it needs to be a csv file.

You can now work locally on your machine, updating the csv file, rendering the result back on your browser.

**Comment by andreyzhm** [comment]
Can we get this PR merged please?

**Comment by sidyatish** [comment]
@jonashartmann, thank you for the PR. 
@jonashartmann and @andreyzhm if we merge this PR, then the file would be available in our [production end point](radar.thoughtworks.com). It would not be acceptable practice to have the sample CSV file always in the hosted application itself. Could you help in updating the configuration such that the `endpoint/sheets/<filename>.<ext>` works only on local/dev run?

Moreover, the config syntax needs to be updated according to the latest webpack version.

Thank you

**Comment by devansh-sharma-tw** [comment]
Closing this PR, as stated above merging this would not be an acceptable practice for our production deployment. We are considering on merging #176 which should provide similar functionality but be limited to a local docker setup only (which will not be affecting our production deployment).
Thank you.

**Pull request closed without merging**
