### PR TITLE
Default radars

### PR DESCRIPTION
**Pull request by jfbenckhuijsen**
Allows to specify default radars instead of the input box. The radars are selectable using buttons. (note: doesn't work yet with the 2022 UI feature toggle)

### CODE REVIEW

**Comment by devansh-sharma-tw** [comment]
Hi @jfbenckhuijsen , thanks for raising this PR!
We feel this change would not match very well with the user flow we have in mind for BYOR. Could you pls share some more of your thoughts on flows or scenarios where this could be more useful ?

Thanks!

**Comment by devansh-sharma-tw** [comment]
Closing this PR as we feel this feature would not match with the user flow we have for BYOR. Please reopen and share your thoughts if there is any specific user flow or scenario you have in mind for this.

Thanks!

**Comment by jfbenckhuijsen** [comment]
Basically the idea is to be able to show the radars of multiple years and allow people to select each year. I.e. act as a page where you can start off from to view the evolution of the various radars. (Sorry about the late reply)

**Comment by devansh-sharma-tw** [comment]
Hi, sorry for the delay in replying.
Thanks for sharing your thoughts on this. We're discussing internally on this and will get back to you.

Thanks!

**Pull request closed without merging**
