### PR TITLE
Improve search

### PR DESCRIPTION
**Pull request by athal7**
- Display blips by quadrant in search results
- Make description content searchable

Screen Shot 2019-12-19 at 12 30 14 PM
Screen Shot 2019-12-19 at 12 30 24 PM

### CODE REVIEW

**Comment by SARAN-thala** [comment]
Hi @athal7 ,

We have reviewed this PR, the basic radar build functionality was broken. Please make sure it won't affect any existing functionality. Please pull the latest code and update your PR.

Thanks

**Comment by athal7** [comment]
Ah sorry for the time waste :-/. 

It wasn’t clear how to validate functionality locally, since there were CORS errors when trying to use the example google sheet, so I thought passing tests was sufficient. 

Any recommendations for local validation?

**Comment by SARAN-thala** [comment]
Here is the [page](https://www.thoughtworks.com/radar/how-to-byor) to describe how to create  BYOR.  Take a look at this and let me know if you facing any issues.

**Comment by athal7** [comment]
Yes I’m familiar, just a challenge with local development / testing because there’s not a way to load a local file. Loading a Google sheets on a locally running radar does not work on master

**Comment by SARAN-thala** [comment]
> Loading a Google sheets on a locally running radar does not work on master

  Could you explain more about this? I didn't get what error are you getting.

BTW, When I tried with example sheet in localhost running radar was working fine.

**Comment by athal7** [comment]
I get CORS errors when using the example sheet on localhost

**Comment by SARAN-thala** [comment]
Did you publish the google sheet?

**Comment by athal7** [comment]
I did, here's a screencast of my experience in case that helps https://drive.google.com/open?id=1PE0T579mUQfJ71SZ8ud6UXGq-S9gOcil

**Comment by SARAN-thala** [comment]
Hi @athal7 ,

This error happens because of the google authentication. You need to set the google API_KEY and  OAuth CLIENT_ID before starting the app server.

To avoid this I raised the PR #130 take a look and use it.

Thanks

**Comment by athal7** [comment]
fantastic, I'm running locally now and will fix this up, thanks @SARAN-thala!

**Comment by athal7** [comment]
@SARAN-thala should be all set now!

**Comment by SARAN-thala** [comment]
Thanks, @athal7 for this PR, we are looking into it.

**Pull request merged**
