### PR TITLE
add flexibility to specify title and subtitle to radar page through params

### PR DESCRIPTION
**Pull request by anilkumarkodi-zz**

### CODE REVIEW

**Comment by gustavz** [comment]
@anilkumarkodi  how would you define title and subtitle in the csv file?

**Comment by anilkumarkodi** [comment]
@gustavz adding title and subtitle as a query param for radar API

eg: https://radar.thoughtworks.com/?title=BUILD%20YOUR%20OWN%20RADAR&subtitle=byor&sheetId=csv-url-path

**Comment by viveksoundrapandi** [comment]
@anilkumarkodi do we have a screenshot of how the end result looks like?

**Comment by Vaishnavij** [comment]
Hello @anilkumarkodi-zz ,

Hope you are doing well!  
The code changes in the PR, has diverged from current implementation. Is it possible to sync them with latest codebase?

Thanks,
BYOR Team

**Pull request closed without merging**
