### PR TITLE
Fix missing blips

### PR DESCRIPTION
**Pull request by filipesabella**
Hello there!

We at SoundCloud started using your lovely tech radar. It works very well, but we noticed a bug when we deployed it.

The current code tries to accommodate all the blips without any collisions on the graph. However, if no suitable spot is found, the code simply removes the blip and the associated description.
Assuming that we rather have a less pleasant graph instead of missing information, I worked on this fix.

It looks like this with this patch and too many blips:
screen shot 2017-06-23 at 15 28 24

There are two main commits in this PR:
- a383a8e: which simply removes the `if` condition.
- 83d8e7c:  which varies the blip size to try and accommodate more of them without overlapping.

I couldn't find any relevant unit tests for distribution feature, please do let me know if it is a problem.

### CODE REVIEW

**Comment by filipesabella** [comment]
Build's definitely broken for unrelated reasons:

```
The command "eval npm install  " failed 3 times.
```

Anything I can do to fix that?

**Comment by thenano** [comment]
I haven't actually checked the travis build, but I'm assuming it builds fine locally, or does it also fail?
And not sure what you mean by "distribution" feature? If it's the publish script that's legacy and no longer used, as far as I know.

**Comment by Rajik** [comment]
Hi @filipesabella, thanks a lot for fixing this issue for us!
I have just checked-in a change to fix the build. Can you please rebase your branch with our master so that the build for this PR passes?

**Comment by filipesabella** [comment]
the build fix worked!

now there's a legit failure that I'm not sure where's coming from, on it :)

**Comment by filipesabella** [comment]
Indeed the problem was the `let`s, weirdly enough. Not sure how it was working on my machine.

Now there's a new CI error that I don't think I can help fix:

```
2.24s$ aws configure set preview.cloudfront true && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
Unable to locate credentials. You can configure credentials by running "aws configure".
The command "aws configure set preview.cloudfront true && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"" exited with 255.
Done. Your build exited with 1.
```

**Comment by Rajik** [comment]
We have pushed something that will fix this error as well. Please rebase once more!

**Comment by filipesabella** [comment]
Yay! Thanks for looking into the build issues :)

**Pull request merged**
