### PR TITLE
Add Google Authentication

### PR DESCRIPTION
**Pull request by BRUNNEL6**
# Summary

The main feature of this PR is an optional Google Authentication which can be configured using environment variables. When the Google Authentication is set up correctly, you will see a "Authorize"-Button, whenever a user enter the website unauthorized.

Authorize Button

This change allows to add private or restricted Google Sheets for the Radar. So the Radar can only be viewed, for people, which are permitted to view the Google Sheet.

# Changes

This PR changed the way of requesting data from a Google Spreadsheet. Before the change, data was requested using a simple GET request. Due to the additional authorization, I decided to use Google GAPI, which handles the authorization and the requesting of a private or public Google Spreadsheet.

The existing unit tests were updated if needed.

# Setup

As described in the README, you can configure the authorization using environment variables or a specific environment file.

| Variable           | Type    | Description                                                                                     |
|--------------------|---------|-------------------------------------------------------------------------------------------------|
| USE_AUTHENTICATION | Boolean | If the user must be authenticated using Google OAuth 2.0 in order to view the site                  |
| API_KEY            | String  | The API Key for the Google OAuth 2.0 Authentication. Gets ignored if USE_AUTHENTICATION=false   |
| CLIENT_ID          | String  | The Client ID for the Google OAuth 2.0 Authentication. Gets ignored if USE_AUTHENTICATION=false |
| ENV_FILE           | String  | The path to the .env-File which have the above environment variables configured                 |

This PR solves issue #60.

This change is backwards compatible, thus dependant can upgrade their applications without changing the Google Sheets.

### CODE REVIEW

**Comment by mohamednajiullah** [comment]
Hello @BRUNNEL6 

> When the Google Authentication is set up correctly, you will see a "Authorize"-Button, whenever a user enter the website unauthorized.

We couldn't quite understand this statement. Our understanding was that once the Google Authentication is set up, sheets protected by organisational limitations would be available for use. 

Would it be possible for you to send us maybe a step-by-step screenshot or a GIF that shows the authorisation process?

Thanks,
The BYOR Team.

**Comment by sachabrants** [comment]
This works great, the Spreadsheet API is not enabled by default in the Google cloud console and it needs to be for this to work.

**Comment by BRUNNEL6** [comment]
@sachabrants Indeed. Correct me if I'm wrong, when following my README guide chapter "Allow Authentication" it should activate the Google Spreadsheet API? Or do I have to update the docs more explicitly?

**Comment by sachabrants** [comment]
My bad, I guess I must have jumped straight to the `Acquiring and using an API key` section and didn't read `Authorizing requests with OAuth 2.0`. It clearly says one needs to activate the API.
Thanks!

**Comment by mohamednajiullah** [comment]
Hello @BRUNNEL6 

We evaluated this PR and had a few observations and questions.

1. The inputSanitizer has been refactored to use an array instead of an object for the blip data. Why was this refactoring necessary?
2. Because of the mentioned refactoring, CSV files hosted in other sources do not seem to be working when used as input.
3. When authorization is turned ON, the user would have to login even if the user wants to just use another hosted file such as a CSV file stored as a GitHub gist and not a Google Sheet. 

Thanks,
The BYOR Team

**Comment by BRUNNEL6** [comment]
Thank you for your response.

> The inputSanitizer has been refactored to use an array instead of an object for the blip data. Why was this refactoring necessary?

Because I had to change the data access interface from the Google Sheet API (now GAPI), as far as I remember. From what I know, the GAPI library does return an array instead of an object when requesting data. I could also map the array items to an object before running the sanitizer, so it would not need to be refactored here:

https://github.com/thoughtworks/build-your-own-radar/blob/4526a13db7135766ccd2adde420cfee9d2260b04/src/util/factory.js#L66-L80

> Because of the mentioned refactoring, CSV files hosted in other sources do not seem to be working when used as input.

I dropped the support for now, because it is not in the scope of the company I work at. Nonetheless I totally understand this should not be dropped for your open source version. I did not re-implement it, because I was not sure if you ever consider merging my PR. If you consider it, I can try and re-implement it.

**Comment by viveksoundrapandi** [comment]
Hey @BRUNNEL6 , 
       Its good to hear that the fork is fully operational in production. Yes, we feel that the PR is valid and would enhance the current behaviour of the project. We are happy to merge once you fix the above issues and re-implement it.

**Comment by SvenC56** [comment]
Is there progress on this pull request?

**Comment by BrunnerLivio** [comment]
Author here (just private account) 

Sorry about not being reactive to this PR. Though it seems to be a variation of this PR has been merged to master, right? 

At least the master version works for us and we are using it from now on and disregarded our fork. 

Thanks a lot for the Thoughtworks Team <3

**Comment by parthparulekar** [comment]
Thank you for contributing with the Google OAuth 2.0 Implementation. 

I have been trying to integrate these additions to my repo for a project, but I am having issues. Although my environment variables are sent prior to 'npm run dev' (env set with setx USE_AUTHENTICATION true e.g.), the authorization seems to be skipped.

Running my app goes straight to the radar itself. I did not want the 'Authorize' button, so I have not created it, and I haven't updated to using GAPI either, so I'm trying to figure what I need to add (what I need to remove).

Here is what I included from your PR:

- loginForm.js
- profileMenu.js
- template.env (docker isn't building off of this, so set local env variables as well)
- factory.js (loggedIn checks)
- Created project w/ Spreadsheets API Keys in Google Cloud (stored in env variables)

Appreciate the help, thanks!

**Comment by arunvelsriram** [comment]
Since the support for private google sheets is implemented in master am closing this PR. Thanks for all the hard work folks.

**Pull request closed without merging**
