### PR TITLE
FIX Replace deprecated and non-functional `istanbul` with `nyc` and upgrade project dependencies

### PR DESCRIPTION
**Pull request by igwejk**
FIX Replace deprecated and non-functional `istanbul` with `nyc` and upgrade project dependencies

- `istanbul` outputs errors and doesn't report coverage. Moreover, the package is no longer maintained. Hence the requirement to replace it
- `prettier-standard --write` actually does not do linting and the `--write` flag is not a supported option
- Updated node version in container to v17.4.0
- Setup python to support npm packages requiring native bindings
- Upgraded npm packages to their latest version
- Removed unused packages including 'mocha' and 'node-sass'
- Due to upgrade of 'jasmine', updated skipped test specs to use the latest supported API for clear reporting of their pending status
- Deleted unexecuted (but problematic) spec/graphing/radar-spec.js test specs
- Add support for development inside same container used for running the application (when developing with VS Code)
- Resolved migration errors due to webpack upgrade from v4 to v5
- Added required dependencies for cypress
- Removed deprecated `file-loader`
- Emit correct asset names and CSS classes scope
- Configure supported `node` engines and `npm` version

An here's the _before and after_ snapshot of the vulnarability status as reported by `npm audit`.
beforeandafter

Co-authored-by: Lars Branzell <lars.branzell@thoughtworks.com>

Closes #236

### CODE REVIEW

**Comment by setchy** [comment]
Such an action-packed PR @igwejk - can't wait for this to drop, particularly the update of node and the npm packages!

Was wondering if there is an opportunity as part of this PR to:
* add an [engines](https://github.com/thoughtworks/build-your-own-radar/pull/237) configuration to `package.json` to list the supported/compatible version of node and npm
* add a `.nvmrc` file which contains the preferred/recommends node version to be used

**Comment by igwejk** [comment]
Thanks for the suggestions @setchy, I'll consider them.

**Comment by igwejk** [comment]
Here's the result of manual smoke test comparing a7acc2a (i.e. `thoughtworks:master`) and e253578 (#237).
Screenshot 2022-01-26 at 09 52 49

**Comment by igwejk** [comment]
The CI report looks good as well. A second pair of eye could be helpful though.

**Review by sidyatish — APPROVED** [review]

**Pull request merged**
