### PR TITLE
Added installation for MSBuild tools and Python

### PR DESCRIPTION
**Pull request by ValeroK**
As part of the compilation of the project it requires MSBuild tools and python. add this lines to the readme file to enable these installations

### CODE REVIEW

**Comment by Rajik** [comment]
Hi,
Thanks for sending us a pull request.
We did not require MSbuild tools and python for building the project. Can you please elaborate more about the environment that required these so that we could understand this PR better?

Thanks.

**Comment by mohamednajiullah** [comment]
Closing this pull request as no response was received.

**Comment by casp4** [comment]
It definitely appears to need python but there's still no mention about it in the readme.

```
C:\Users\Dev\Documents\build-your-own-radar>npm install

> node-sass@4.13.0 install C:\Users\Dev\Documents\build-your-own-radar\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.0/win32-x64-83_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.13.0/win32-x64-83_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> cypress@3.7.0 postinstall C:\Users\Dev\Documents\build-your-own-radar\node_modules\cypress
> node index.js --exec install

Installing Cypress (version: 3.7.0)

 √  Downloaded Cypress
 √  Unzipped Cypress
 √  Finished Installation C:\Users\Dev\AppData\Local\Cypress\Cache\3.7.0

You can now open Cypress by running: node_modules\.bin\cypress open

https://on.cypress.io/installing-cypress


> node-sass@4.13.0 postinstall C:\Users\Dev\Documents\build-your-own-radar\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\Dev\Documents\build-your-own-radar\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Dev\\Documents\\build-your-own-radar\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.14.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Dev\Documents\build-your-own-radar\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Dev\Documents\build-your-own-radar\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Dev\Documents\build-your-own-radar\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Dev\Documents\build-your-own-radar\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Dev\Documents\build-your-own-radar\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Dev\Documents\build-your-own-radar\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Dev\Documents\build-your-own-radar\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Dev\Documents\build-your-own-radar\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Dev\Documents\build-your-own-radar\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Dev\Documents\build-your-own-radar\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Dev\Documents\build-your-own-radar\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Dev\Documents\build-your-own-radar\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Dev\Documents\build-your-own-radar\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Dev\Documents\build-your-own-radar\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Dev\Documents\build-your-own-radar\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Dev\Documents\build-your-own-radar\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Dev\Documents\build-your-own-radar\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Dev\Documents\build-your-own-radar\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Dev\Documents\build-your-own-radar\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Dev\Documents\build-your-own-radar\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Dev\Documents\build-your-own-radar\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Dev\Documents\build-your-own-radar\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Dev\Documents\build-your-own-radar\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Dev\Documents\build-your-own-radar\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Dev\Documents\build-your-own-radar\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Dev\Documents\build-your-own-radar\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Users\Dev\Documents\build-your-own-radar\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:183:21)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Dev\\Documents\\build-your-own-radar\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\Dev\Documents\build-your-own-radar\node_modules\node-sass
gyp ERR! node -v v14.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.13.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.13.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dev\AppData\Roaming\npm-cache\_logs\2021-04-01T01_22_20_769Z-debug.log
```

**Comment by casp4** [comment]
switched to node 12.21.0 and now it installs fine without needing Python.

image

**Comment by sprankle** [comment]
Hello - for anyone that comes across this problem:

Specify SASS in the package.json
```json
{
  "devDependencies": {
    "sass": "^1.22.10",
  }
}
```

Cause:
load-sass is looking for a sass runtime and is trying to use node-sass when on windows. Dart sass is intended and can be prioritized by specifying it in the devDependencies.

**Pull request closed without merging**
