### PR TITLE
converted googlesheets to local csv file - located in src/resources/data/data.csv

### PR DESCRIPTION
**Pull request by andy9876**

### CODE REVIEW

**Comment by arjunm183** [comment]
Is there a way to upload the data via csv file instead of pointing to Google Sheets. ?

Kindly help me.

**Comment by arjunm183** [comment]
Can i upload the file in a webbrowser and then point it in the URL path. Can you help me with this?

**Comment by andy9876** [comment]
Hello - this is what this pull request solves for, provides a csv file instead of google sheets.  to upload the file to a remote location and then have the code access it would require changes.

**Comment by deekayw0n** [comment]
This PR also addresses this issue:

ERROR in ./~/xmlhttprequest/lib/XMLHttpRequest.js
Module not found: Error: Cannot resolve module 'child_process' in /app/node_modules/xmlhttprequest/lib
 @ ./~/xmlhttprequest/lib/XMLHttpRequest.js 15:12-36

If for some reason this PR is not accepted, changes to webpack.config.js, namely: 
+    externals:[{
+               xmlhttprequest: '{XMLHttpRequest:XMLHttpRequest}'
+       }],
+
should be added via a targeted PR sooner than later ;)

**Comment by SARAN-thala** [comment]
Hi Andy,
Thanks for sending this PR to us.
From your commits, we understand that you are trying to build the radar using a local CSV file instead of providing a google sheets URL for the radar data. But this PR completely removes the use of Google sheets and it depends only on the local CSV file.
We would like to have both the functionalities integrated - in the sense we would want the data to come from Google sheets or from CSV file - but not remove the usage of Google sheets itself as it would break the SaaS version of this product.
Can you please modify your PR in such a way that the CSV functionality is only added to the existing system but not remove its existing workflow?

Thanks,
ThoughtWorks team

**Comment by andy9876** [comment]
Yes, I will work on that.

**Comment by arjunm183** [comment]
@andy9876 
It would be a great piece of work if you could add the functionality by having option of csv.
Hope it would be delivered soon.

**Comment by andy9876** [comment]
Hey Arunm183 - yes I am working on this.  thanks

**Comment by andy9876** [comment]
ok, I have added in the google sheets functionality.  I basically added a checkbox on the main page if they want to use a local file option in addition to the existing text box for google sheets.  let me know what you think!

**Comment by andy9876** [comment]
@SARAN-thala - I've added in a local csv option in addition to the google sheets functional on the main page that the users can toggle via a checkbox.  let me know what you think.

**Comment by mohamednajiullah** [comment]
Hi @andy9876,

We're currently reviewing your pull request. Once we've finished, we'll get back to you.

Thanks,
ThoughtWorks Team

**Comment by SARAN-thala** [comment]
Hi @andy9876 

Thank you for the pull request. We went through it. We've identified a few issues.

1.  There were two bug fixes that were done recently.

    - [Fix to remove bug - Print this radar contains empty pages when there is no element in some rings.](https://github.com/thoughtworks/build-your-own-radar/pull/27)

    - [Fix missing blips](https://github.com/thoughtworks/build-your-own-radar/pull/26)

These bug fixes seem to have been reverted in your pull request. Can you please rebase your branch with our master? 

2. The pull request always uses the same file (data.csv) that is stored locally inside the solution. This won't work on the website [radar.thoughtworks.com](radar.thoughtworks.com) (the SaaS offering of BYOR) as it would try to use the same file(data.csv) instead of the file that the user would like to use.

3. The created Radar does not have the Powered By ThoughtWorks logo.

Thanks,
ThoughtWorks Team

**Comment by andy9876** [comment]
Thanks. I will make these changes and update the pull request. 

Thanks

**Comment by andy9876** [comment]
@SARAN-thala sorry for the delay.  I see you guys have merged another pull request that allows a URL that points to a CSV file.  given that do you still need me to make the updates above or should we close this pull request?

**Comment by mohamednajiullah** [comment]
@andy9876 , 

Considering a similar functionality has already been merged to the master, I think we should close this request.

Thank you for helping us improving BYOR.
ThoughtWorks Team

**Comment by mattjtodd** [comment]
@andy9876 @mohamednajiullah

**Comment by andy9876** [comment]
@matttodd another pull request was merged that solves for the CSV, this pull request should be closed.
@hkurosawa can you answer matttodd's question above?  I believe the answer is yes

**Comment by hkurosawa** [comment]
@andy9876 
yes, it uses d3.csv() function to read the csv so it should be able to handle the file schema basically but browser's security policy may prohibit it.
(refer: https://stackoverflow.com/questions/15417437/d3-js-loading-local-data-file-from-file)

But i think it's a matter of a browser's security policy and not the code and it depends on the use-case if it satisfies the needs.

**Comment by mattjtodd** [comment]
@hkurosawa One use case that I can't see how to do really easily is the ability to build a docker image with the csv file added and loaded from a static location so that the both the Dockerfile and csv file can live in VCS and be deployed via CI / CD pipelines.

Any thoughts about how this could work?

**Pull request closed without merging**
